import "./bootstrap";

// Importa o motor da Lucide e os ícones que você quer usar
import {
    createIcons,
    CircleAlert,
    TriangleAlert,
    LayoutDashboard,
    Wrench,
    Car,
    SearchCode,
    Package,
    Briefcase,
    Users,
    LogOut,
    ClipboardList,
    Check,
    Clock,
    CheckCircle,
    ListOrdered,
    Eye,
    ArrowRightCircle,
    ChevronRight,
    PackageSearch,
    CheckCircle2,
    Timer,
    Hammer,
    Search,
    Info,
    Filter,
    Lightbulb,
    BarChart3,
    PlusCircle,
    Save,
    Camera,
    ShieldAlert,
    MessagesSquare,
    HelpCircle,
    ArrowLeft,
    ArrowRight,
    Edit3,
    UserCog,
    ClipboardCheck,
    History,
    Edit2,
    SearchX,
    ShieldOff,
    ShieldCheck,
    FolderOpen,
    User,
    PackageX,
    Trash2,
    Shield,
    PackagePlus,
    ClipboardX,
    PlusSquare,
    UserPlus,
    UserX,
} from "lucide";

// Inicializa os ícones
document.addEventListener("DOMContentLoaded", () => {
    createIcons({
        icons: {
            CircleAlert,
            TriangleAlert,
            LayoutDashboard,
            Wrench,
            Car,
            SearchCode,
            Package,
            Briefcase,
            Users,
            LogOut,
            ClipboardList,
            Check,
            Clock,
            CheckCircle,
            ListOrdered,
            Eye,
            ArrowRightCircle,
            ChevronRight,
            PackageSearch,
            CheckCircle2,
            Timer,
            Hammer,
            Search,
            Info,
            Filter,
            Lightbulb,
            BarChart3,
            PlusCircle,
            Save,
            Camera,
            ShieldAlert,
            MessagesSquare,
            HelpCircle,
            ArrowLeft,
            ArrowRight,
            Edit3,
            UserCog,
            ClipboardCheck,
            History,
            Edit2,
            SearchX,
            ShieldOff,
            ShieldCheck,
            FolderOpen,
            User,
            PackageX,
            Trash2,
            Shield,
            PackagePlus,
            ClipboardX,
            CheckCircle,
            PlusSquare,
            UserPlus,
            UserCog,
            UserX,
        },
        attrs: {
            "stroke-width": 2,
            class: "lucide-icon", // Classe opcional para estilização global
        },
    });
});
